name: Build CIVideo Application

on:
  pull_request:
    branches: [ main ]

env:
  APPLICATION_SECRET_FILE_PATH: src/main/resources/application-secret.yml
  APPLE_AUTH_KEY_FILE_PATH: src/main/resources/key/AuthKey.p8

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          cat << EOF >> ${{ env.APPLICATION_SECRET_FILE_PATH }}
          ${{ secrets.APPLICATION_SECRET }}
          EOF
          mkdir src/main/resources/key
          cat << EOF >> ${{ env.APPLE_AUTH_KEY_FILE_PATH }}
          ${{ secrets.APPLE_AUTH_KEY }}
          EOF
          ./gradlew test --no-daemon
