name: Build CIVideo Application

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: |
          echo ${{ secrets.APPLICATION_SECRET }} >> src/main/java/com/ehago/kreamzone/resource/application-secret.yml
          ./gradlew build --no-daemon
